#!/bin/bash

minAge="+60" # days
crtDir="/etc/letsencrypt/live"
baseDir="/opt"
certbotGit="https://github.com/certbot/certbot"
certbotDir="$baseDir/certbot"
certbot="$certbotDir/certbot-auto"

err(){
  echo "error: $*"
  exit 1
}

noCrtDir(){
  echo "To create create new certificate run"
  echo "certbot-auto certonly --webroot -w <docRoot> -d <domain> [-d domainalias>]"
  exit 0
}

# verify install
if [ ! -d "$baseDir" ]; then
  mkdir -p "$baseDir" || err "$baseDir missing and cant create"
fi
if [ ! -d "$certbotDir" ]; then
  git=$(which git)
  if [ -z "$git" ]; then
    # git missing, fix it
    apt-get -y install git
    git=$(which git)||err "install git manualy"
  fi
  $git clone "$certbotGit" "$certbotDir"||err "git cloen failed"
  [ -f "/usr/local/sbin/certbot-auto" ]||ln -s "$certbot" "/usr/local/sbin/certbot-auto"
fi

# find ex certs
[ -d "$crtDir" ]||noCrtDir
renew=$(find "$crtDir" -maxdepth 1 -mindepth 1 -type d -mtime $minAge|wc -l)

if [ $renew -eq 0 ]; then
  # nothing to renew
  exit 0
fi

# renew certificates
$certbot renew --webroot --quiet 

# reload webserver
nginx=$(which nginx)&&$nginx -sreload
apache2ctl=$(which apache2ctl)&&$apache2ctl -k graceful
