#!/bin/bash

PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"

minAge="+60" # days
crtDir="/etc/letsencrypt/live"

err(){
  echo "error: $*"
  exit 1
}

noCrtDir(){
  echo "To create create new certificate run"
  echo "certbot certonly --webroot -w <docRoot> -d <domain> [-d domainalias>]"
  exit 0
}

# verify install
certbot=$(which certbot-auto certbot|head -n1)
if [ -z "$certbot" ]; then
  apt-get -yq install software-properties-common
  addAptRepository=$(which add-apt-repository)||err "software-properties-common missing"
  $addAptRepository -yq ppa:certbot/certbot||err "add certbot ppa manualy"
  apt-get -yq install certbot
  apt-get -q update
  certbot=$(which certbot)||err "install certbot manualy"
fi

# find ex certs
[ -d "$crtDir" ]||noCrtDir
renew=$(find "$crtDir" -maxdepth 1 -mindepth 1 -type d -mtime $minAge|wc -l)

if [ $renew -eq 0 ]; then
  # nothing to renew
  exit 0
fi

# renew certificates
$certbot renew --webroot --quiet 

# reload webserver
if nginx=$(which nginx); then
  if ps ax | grep -q nginx; then
    $nginx -sreload
  fi
fi
if apache2ctl=$(which apache2ctl); then
  if ps ax | grep -q "apache2 -k start"; then
    $apache2ctl -k graceful
  fi
fi
